services:
  xstrm-nginx:
    image: nginx:stable
    container_name: xstrm-nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/conf.d/includes:/opt/xstrm-suite/nginx/conf.d/includes:ro
      - ./data/nginx-log:/var/log/nginx
      - ./data/nginx-cache:/var/cache/nginx
      - ${XSTRM_CERT_DIR:-./config/cert}:/etc/nginx/cert:ro
