version: '3.8'

services:
  xstrm-nginx:
    image: nginx:stable
    container_name: xstrm-nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/xstrm-suite/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/xstrm-suite/nginx/conf.d:/etc/nginx/conf.d:ro
      - /opt/xstrm-suite/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - /opt/xstrm-suite/nginx/conf.d/includes:/opt/xstrm-suite/nginx/conf.d/includes:ro
      - /opt/xstrm-suite/web:/opt/xstrm-suite/web:ro
      - /opt/xstrm-suite/data/nginx-log:/var/log/nginx
      - /opt/xstrm-suite/data/nginx-cache:/var/cache/nginx
      - /www/server/panel/vhost/cert/your-domain.example.com:/www/server/panel/vhost/cert/your-domain.example.com:ro

