server {
    listen 8095;
    server_name _;

    client_max_body_size 0;

    location = /admin/xstrm {
        return 302 /admin/xstrm/;
    }

    location /admin/xstrm/ {
        alias /opt/xstrm-suite/web/admin/;
        index index.html;
        try_files $uri $uri/ /admin/xstrm/index.html;
    }

    location /api/admin/xstrm/ {
        proxy_pass http://127.0.0.1:18095;
        include /opt/xstrm-suite/nginx/conf.d/includes/proxy-header.conf;
    }

    location / {
        proxy_pass http://127.0.0.1:8095;
        include /opt/xstrm-suite/nginx/conf.d/includes/proxy-header.conf;
    }
}
