server {
    listen 8095;
    server_name _;

    client_max_body_size 0;

    location / {
        proxy_pass http://127.0.0.1:8095;
        include /opt/xstrm-suite/nginx/conf.d/includes/proxy-header.conf;
    }
}
